<script setup>
import { computed, onBeforeUnmount, reactive, ref, watch } from "vue";
import { useRoute, useRouter } from "vue-router";
import EditableChildTable from "@/components/forms/EditableChildTable.vue";
import FormField from "@/components/forms/FormField.vue";
import ErrorState from "@/components/feedback/ErrorState.vue";
import PermissionDenied from "@/components/feedback/PermissionDenied.vue";
import PageContainer from "@/components/layout/PageContainer.vue";
import { getEntityForm, saveEntityForm } from "@/services/entityForms.js";

const route = useRoute(); const router = useRouter(); const entityKey = computed(() => route.meta.entityKey); const name = computed(() => route.params.name || null);
const data = ref(null); const loading = ref(false); const saving = ref(false); const error = ref(null); const saveError = ref(null); const permissionDenied = ref(false); const form = reactive({}); const fieldErrors = reactive({}); let controller; let initial = "";
function resetForm(values) { Object.keys(form).forEach((key) => delete form[key]); Object.assign(form, JSON.parse(JSON.stringify(values || {}))); initial = JSON.stringify(form); }
const dirty = computed(() => initial && JSON.stringify(form) !== initial);
async function load() { controller?.abort(); controller = new AbortController(); loading.value = true; error.value = null; saveError.value = null; permissionDenied.value = false; try { data.value = await getEntityForm(entityKey.value, name.value, controller.signal); resetForm(data.value.document); } catch (requestError) { permissionDenied.value = requestError.permissionDenied; error.value = requestError; } finally { if (!controller.signal.aborted) loading.value = false; } }
watch(() => route.fullPath, load, { immediate: true }); onBeforeUnmount(() => controller?.abort());
function validate() { Object.keys(fieldErrors).forEach((key) => delete fieldErrors[key]); saveError.value = null; for (const field of data.value.entity.fields) if (field.required && !form[field.fieldname]) fieldErrors[field.fieldname] = `${field.label} is required.`; if (data.value.entity.child_tables?.items && !form.items?.length) fieldErrors.items = "At least one item is required."; if (entityKey.value === "items") { const purchase = Number(form.custom_purchase_price || 0), additional = Number(form.custom_additional_cost || 0), retail = Number(form.custom_retail_profit_percentage || 0), wholesale = Number(form.custom_wholesale_profit_percentage || 0); if ([purchase, additional, retail, wholesale].some((value) => value < 0)) fieldErrors.custom_purchase_price = "Cost and percentage values cannot be negative."; if (wholesale > retail) fieldErrors.custom_wholesale_profit_percentage = "Wholesale percentage cannot exceed retail percentage."; } return !Object.keys(fieldErrors).length; }
async function save() { if (!validate() || saving.value) return; saving.value = true; error.value = null; try { const requestId = crypto.randomUUID?.() || `${Date.now()}-${Math.random()}`; const result = await saveEntityForm(entityKey.value, form, name.value, requestId); initial = JSON.stringify(form); await router.push(result.route); } catch (requestError) { if (requestError.type === "ValidationError" || requestError.status === 417) { saveError.value = requestError.message; } else { error.value = requestError; } } finally { saving.value = false; } }
function cancel() { if (!dirty.value || window.confirm("Discard unsaved changes?")) router.push(data.value?.entity.back_route || "/home"); }
const pricing = computed(() => { const total = Number(form.custom_purchase_price || 0) + Number(form.custom_additional_cost || 0); return { total, retail: total * (1 + Number(form.custom_retail_profit_percentage || 0) / 100), wholesale: total * (1 + Number(form.custom_wholesale_profit_percentage || 0) / 100) }; });
</script>
<template><PageContainer><PermissionDenied v-if="permissionDenied" message="You do not have permission to create or edit this record." /><ErrorState v-else-if="error" title="Unable to load form" :message="error.message" /><div v-else-if="loading || !data" class="ref-detail-loading"><span class="ref-spinner"/><strong>Loading form…</strong></div><form v-else class="ref-form-page" @submit.prevent="save"><header class="ref-entity-page__header"><div><span class="ref-entity-page__eyebrow">RETAIL ERP FORM</span><h1>{{ name ? `Edit ${data.entity.title}` : `New ${data.entity.title}` }}</h1><p>{{ name ? 'Only approved draft and master-data changes are available.' : 'Fields are validated by ERPNext before saving.' }}</p></div><div class="ref-form-actions"><button class="ref-button ref-button--secondary" type="button" :disabled="saving" @click="cancel">Cancel</button><button class="ref-button ref-button--primary" type="submit" :disabled="saving">{{ saving ? 'Saving…' : 'Save' }}</button></div></header><div v-if="saveError || Object.keys(fieldErrors).length" class="ref-validation-summary" role="alert"><strong>Fix the highlighted fields before saving.</strong><p v-if="saveError">{{ saveError }}</p><p v-for="(message, key) in fieldErrors" :key="key">{{ message }}</p></div><section v-for="section in data.entity.sections" :key="section.key" class="ref-form-section"><h2>{{ section.title }}</h2><div class="ref-form-grid"><FormField v-for="field in data.entity.fields.filter((entry) => entry.section === section.key)" :key="field.fieldname" v-model="form[field.fieldname]" :field="field" :entity-key="entityKey" :error="fieldErrors[field.fieldname]" /></div></section><section v-if="entityKey === 'items'" class="ref-pricing-preview"><h2>Pricing Preview</h2><strong>Total Cost: {{ pricing.total.toLocaleString(undefined, { minimumFractionDigits: 2 }) }}</strong><strong>Retail: {{ pricing.retail.toLocaleString(undefined, { minimumFractionDigits: 2 }) }}</strong><strong>Wholesale: {{ pricing.wholesale.toLocaleString(undefined, { minimumFractionDigits: 2 }) }}</strong></section><div :class="{ 'ref-form-section--error': fieldErrors.items }"><EditableChildTable v-for="(table, tableName) in data.entity.child_tables" :key="tableName" :model-value="form[tableName] || []" :table="table" :entity-key="entityKey" :errors="fieldErrors" :allow-add="['sales_orders','delivery_notes','sales_invoices','payment_entries'].includes(entityKey)" @update:model-value="form[tableName] = $event" /></div></form></PageContainer></template>
