<script setup>
import { computed, onBeforeUnmount, ref, watch } from "vue";
import { useRoute } from "vue-router";
import ErrorState from "@/components/feedback/ErrorState.vue";
import PermissionDenied from "@/components/feedback/PermissionDenied.vue";
import PageContainer from "@/components/layout/PageContainer.vue";
import EntityActions from "@/components/detail/EntityActions.vue";
import { getMappedDraftDetail } from "@/services/entityForms.js";
const route = useRoute(); const entityKey = computed(() => route.meta.entityKey);
const data = ref(null); const error = ref(null); const loading = ref(false); const denied = ref(false); let controller;
async function load() { controller?.abort(); controller = new AbortController(); loading.value = true; error.value = null; denied.value = false; try { data.value = await getMappedDraftDetail(entityKey.value, route.params.name, controller.signal); } catch (e) { denied.value = e.permissionDenied; error.value = e; } finally { loading.value = false; } }
watch(() => route.fullPath, load, { immediate: true }); onBeforeUnmount(() => controller?.abort());
</script>
<template><PageContainer><PermissionDenied v-if="denied"/><ErrorState v-else-if="error" title="Unable to load document" :message="error.message"/><div v-else-if="loading || !data" class="ref-detail-loading"><span class="ref-spinner"/><strong>Loading document…</strong></div><div v-else class="ref-form-page"><header class="ref-entity-page__header"><div><span class="ref-entity-page__eyebrow">RETAIL ERP DOCUMENT</span><h1>{{ data.entity.title }} {{ data.document.name }}</h1><p>{{ data.status || 'Draft' }} · {{ data.document.customer }}</p></div><RouterLink v-if="data.permissions.can_write && data.docstatus === 0" class="ref-button ref-button--primary" :to="`${data.entity.back_route}/${encodeURIComponent(data.document.name)}/edit`">Edit Draft</RouterLink></header><section class="ref-form-section"><h2>Totals</h2><div class="ref-pricing-preview"><strong>Net: {{ data.totals.currency }} {{ Number(data.totals.net_total || 0).toLocaleString() }}</strong><strong>Taxes: {{ data.totals.currency }} {{ Number(data.totals.taxes || 0).toLocaleString() }}</strong><strong>Grand Total: {{ data.totals.currency }} {{ Number(data.totals.grand_total || 0).toLocaleString() }}</strong><strong v-if="data.totals.paid_amount != null">Paid: {{ data.totals.currency }} {{ Number(data.totals.paid_amount || 0).toLocaleString() }}</strong></div></section><section class="ref-editable-table"><h2>Items</h2><div class="ref-child-table-wrap"><table class="ref-child-table"><thead><tr><th>Item</th><th>Quantity</th><th>Warehouse</th><th>Rate</th><th>Amount</th></tr></thead><tbody><tr v-for="row in data.document.items || []" :key="row.name"><td>{{ row.item_name || row.item_code }}</td><td>{{ row.qty }} {{ row.uom }}</td><td>{{ row.warehouse }}</td><td>{{ row.rate }}</td><td>{{ row.amount }}</td></tr></tbody></table></div></section><EntityActions :entity-key="entityKey" :document="data.document" @refresh="load" /></div></PageContainer></template>
