<script setup>
import { computed, ref } from "vue";
import { getOutstandingReferences } from "@/services/payment.js";
const props = defineProps({ modelValue: { type: Array, default: () => [] }, form: { type: Object, required: true } });
const emit = defineEmits(["update:modelValue"]);
const open = ref(false); const loading = ref(false); const error = ref(null); const rows = ref([]); const selected = ref(new Set());
const hasParty = computed(() => Boolean(props.form.party_type && props.form.party && props.form.company));
function normalize(row) { return { ...row, reference_doctype: row.reference_doctype || row.voucher_type, reference_name: row.reference_name || row.voucher_no, allocated_amount: Number(row.allocated_amount || 0), outstanding_amount: Number(row.outstanding_amount || row.outstanding || 0), total_amount: Number(row.total_amount || row.invoice_amount || 0) }; }
async function load() { if (!hasParty.value) { error.value = "Select Party Type, Party and Company first."; open.value = true; return; } open.value = true; loading.value = true; error.value = null; try { const result = await getOutstandingReferences({ party_type: props.form.party_type, party: props.form.party, company: props.form.company, payment_type: props.form.payment_type, get_outstanding_invoices: 1, get_orders_to_be_billed: 1 }); rows.value = (result || []).map(normalize); selected.value = new Set(rows.value.map((_row, index) => index)); } catch (e) { error.value = e.message; } finally { loading.value = false; } }
function toggle(index) { const next = new Set(selected.value); next.has(index) ? next.delete(index) : next.add(index); selected.value = next; }
function selectAll() { selected.value = new Set(rows.value.map((_row, index) => index)); }
function clearSelection() { selected.value = new Set(); }
function autoAllocate() { let remaining = Number(props.form.paid_amount || props.form.received_amount || 0); rows.value = rows.value.map((row, index) => { if (!selected.value.has(index)) return { ...row, allocated_amount: 0 }; const amount = Math.max(0, Math.min(row.outstanding_amount, remaining)); remaining -= amount; return { ...row, allocated_amount: Number(amount.toFixed(2)) }; }); }
function apply() { const refs = rows.value.filter((_row, index) => selected.value.has(index) && Number(_row.allocated_amount) > 0).map((row) => ({ reference_doctype: row.reference_doctype, reference_name: row.reference_name, due_date: row.due_date, total_amount: row.total_amount, outstanding_amount: row.outstanding_amount, allocated_amount: Number(row.allocated_amount), exchange_rate: row.exchange_rate, payment_term: row.payment_term })); emit("update:modelValue", refs); open.value = false; }
</script>
<template><div class="ref-allocation"><button type="button" class="ref-button ref-button--secondary" @click="load">Get Outstanding Invoices / Orders</button><div v-if="open" class="ref-preview-modal" role="dialog" aria-modal="true"><div class="ref-preview-modal__backdrop" @click="open = false"/><section><header><div><span class="ref-entity-page__eyebrow">PAYMENT ALLOCATION</span><h2>Outstanding references</h2></div><button type="button" @click="open = false">×</button></header><p v-if="error" class="ref-action-error">{{ error }}</p><div v-else-if="loading" class="ref-detail-loading"><span class="ref-spinner"/><strong>Loading outstanding documents…</strong></div><div v-else-if="!rows.length" class="ref-child-empty">No outstanding references were found.</div><div v-else class="ref-allocation-table"><div class="ref-allocation-toolbar"><button type="button" class="ref-button ref-button--secondary" @click="selectAll">Select All</button><button type="button" class="ref-button ref-button--secondary" @click="clearSelection">Clear Selection</button><button type="button" class="ref-button ref-button--secondary" @click="autoAllocate">Auto Allocate</button></div><label v-for="(row, index) in rows" :key="`${row.reference_doctype}-${row.reference_name}`" class="ref-allocation-row"><input type="checkbox" :checked="selected.has(index)" @change="toggle(index)"/><span><strong>{{ row.reference_doctype }} {{ row.reference_name }}</strong><small>Due {{ row.due_date || '—' }} · Total {{ row.total_amount }} · Outstanding {{ row.outstanding_amount }}</small></span><input v-model.number="row.allocated_amount" type="number" min="0" :max="row.outstanding_amount" step="0.01" aria-label="Allocated amount"/></label></div><footer><button type="button" class="ref-button ref-button--secondary" @click="open = false">Cancel</button><button type="button" class="ref-button ref-button--primary" :disabled="loading || Boolean(error)" @click="apply">Apply Allocation</button></footer></section></div></div></template>
