"""Server-owned clean-route registry for priority Retail ERP coverage.

The values in this module are presentation and routing declarations only. They
never grant access: every resolver and API rechecks Frappe permissions.
"""

from __future__ import annotations

from collections import defaultdict


MODULES = {
	"home": {"label": "Home", "description": "Your permitted records, quick actions and recent activity.", "accent": "blue"},
	"sales": {"label": "Sales", "description": "Customers, quotations, orders, delivery and invoicing.", "accent": "blue"},
	"purchases": {"label": "Purchases", "description": "Suppliers, sourcing, ordering, receipts and supplier invoices.", "accent": "orange"},
	"inventory": {"label": "Inventory", "description": "Products, warehouses, stock movements and traceability.", "accent": "green"},
	"finance": {"label": "Finance", "description": "Accounting documents, payments, reconciliation and financial reports.", "accent": "purple"},
	"crm": {"label": "CRM", "description": "Leads, opportunities, contacts, campaigns and customer relationships.", "accent": "pink"},
	"operations": {"label": "Operations", "description": "Projects, assets, quality, support and manufacturing operations.", "accent": "turquoise"},
	"reports": {"label": "Reports", "description": "Permission-aware ERPNext operational and financial reports.", "accent": "dark-blue"},
	"admin": {"label": "Admin", "description": "Restricted users, permissions, setup and system monitoring.", "accent": "purple"},
}


# Clean path -> feature. Handcrafted paths are deliberately absent; the static
# route registry resolves them before consulting this table.
ENTITY_ROUTES = {
	# Sales
	"/sales/quotations": {"doctype": "Quotation", "module": "sales", "classification": "transaction_provisional"},
	# Purchases
	"/purchases/suppliers": {"doctype": "Supplier", "module": "purchases"},
	"/purchases/material-requests": {"doctype": "Material Request", "module": "purchases", "classification": "transaction_provisional"},
	"/purchases/requests-for-quotation": {"doctype": "Request for Quotation", "module": "purchases", "classification": "transaction_provisional"},
	"/purchases/supplier-quotations": {"doctype": "Supplier Quotation", "module": "purchases", "classification": "transaction_provisional"},
	"/purchases/orders": {"doctype": "Purchase Order", "module": "purchases", "classification": "transaction_provisional"},
	"/purchases/receipts": {"doctype": "Purchase Receipt", "module": "purchases", "classification": "transaction_provisional"},
	"/purchases/invoices": {"doctype": "Purchase Invoice", "module": "purchases", "classification": "transaction_provisional"},
	# Inventory
	"/inventory/item-groups": {"doctype": "Item Group", "module": "inventory", "view": "tree"},
	"/inventory/brands": {"doctype": "Brand", "module": "inventory"},
	"/inventory/warehouses": {"doctype": "Warehouse", "module": "inventory", "view": "tree"},
	"/inventory/item-prices": {"doctype": "Item Price", "module": "inventory"},
	"/inventory/price-lists": {"doctype": "Price List", "module": "inventory"},
	"/inventory/uoms": {"doctype": "UOM", "module": "inventory"},
	"/inventory/stock-entries": {"doctype": "Stock Entry", "module": "inventory", "classification": "transaction_provisional"},
	"/inventory/reconciliations": {"doctype": "Stock Reconciliation", "module": "inventory", "classification": "specialised_provisional"},
	"/inventory/serial-numbers": {"doctype": "Serial No", "module": "inventory"},
	"/inventory/batches": {"doctype": "Batch", "module": "inventory"},
	# Finance
	"/finance/chart-of-accounts": {"doctype": "Account", "module": "finance", "view": "tree"},
	"/finance/journal-entries": {"doctype": "Journal Entry", "module": "finance", "classification": "transaction_provisional"},
	"/finance/payment-requests": {"doctype": "Payment Request", "module": "finance", "classification": "transaction_provisional"},
	"/finance/cost-centers": {"doctype": "Cost Center", "module": "finance", "view": "tree"},
	"/finance/modes-of-payment": {"doctype": "Mode of Payment", "module": "finance"},
	# CRM
	"/crm/leads": {"doctype": "Lead", "module": "crm"},
	"/crm/opportunities": {"doctype": "Opportunity", "module": "crm"},
	"/crm/contacts": {"doctype": "Contact", "module": "crm"},
	"/crm/addresses": {"doctype": "Address", "module": "crm"},
	"/crm/campaigns": {"doctype": "Campaign", "module": "crm"},
	"/crm/appointments": {"doctype": "Appointment", "module": "crm"},
	"/crm/territories": {"doctype": "Territory", "module": "crm", "view": "tree"},
	"/crm/customer-groups": {"doctype": "Customer Group", "module": "crm", "view": "tree"},
	"/crm/sales-people": {"doctype": "Sales Person", "module": "crm", "view": "tree"},
	# Operations
	"/operations/projects": {"doctype": "Project", "module": "operations"},
	"/operations/tasks": {"doctype": "Task", "module": "operations", "classification": "specialised_provisional"},
	"/operations/assets": {"doctype": "Asset", "module": "operations"},
	"/operations/asset-movements": {"doctype": "Asset Movement", "module": "operations", "classification": "transaction_provisional"},
	"/operations/quality-inspections": {"doctype": "Quality Inspection", "module": "operations", "classification": "transaction_provisional"},
	"/operations/support/issues": {"doctype": "Issue", "module": "operations"},
	"/operations/departments": {"doctype": "Department", "module": "operations", "view": "tree"},
	"/operations/designations": {"doctype": "Designation", "module": "operations"},
	"/operations/manufacturing/boms": {"doctype": "BOM", "module": "operations", "classification": "specialised_provisional"},
	"/operations/manufacturing/production-plans": {"doctype": "Production Plan", "module": "operations", "classification": "specialised_provisional"},
	"/operations/manufacturing/work-orders": {"doctype": "Work Order", "module": "operations", "classification": "specialised_provisional"},
	"/operations/manufacturing/job-cards": {"doctype": "Job Card", "module": "operations", "classification": "specialised_provisional"},
	"/operations/manufacturing/operations": {"doctype": "Operation", "module": "operations"},
	"/operations/manufacturing/workstations": {"doctype": "Workstation", "module": "operations"},
	"/operations/subcontracting/orders": {"doctype": "Subcontracting Order", "module": "operations", "classification": "specialised_provisional"},
	"/operations/subcontracting/receipts": {"doctype": "Subcontracting Receipt", "module": "operations", "classification": "specialised_provisional"},
	# Restricted administration. System Manager checks are additionally applied.
	"/admin/users": {"doctype": "User", "module": "admin", "roles": ("System Manager",)},
	"/admin/roles": {"doctype": "Role", "module": "admin", "roles": ("System Manager",)},
	"/admin/companies": {"doctype": "Company", "module": "admin", "roles": ("System Manager",)},
	"/admin/warehouses": {"doctype": "Warehouse", "module": "admin", "roles": ("System Manager",), "view": "tree"},
	"/admin/price-lists": {"doctype": "Price List", "module": "admin", "roles": ("System Manager",)},
	"/purchases/supplier-groups": {"doctype": "Supplier Group", "module": "purchases", "view": "tree"},
}


# --- Generated in-scope DocType routes (Full Feature Parity, batch: masters) ---
# Curated standard parent DocTypes served read/write by the universal metadata
# engine with standard Frappe permissions. Ledger/system tables, single
# Settings/Tools and the POS family are intentionally excluded. Status is
# generated_provisional until behavioural verification exists.
_GENERATED_ENTITY_ROUTES = {
	"/crm/address-template": {"doctype": "Address Template", "module": "crm", "classification": "generated_provisional"},
	"/crm/competitor": {"doctype": "Competitor", "module": "crm", "classification": "generated_provisional"},
	"/crm/contract": {"doctype": "Contract", "module": "crm", "classification": "generated_provisional"},
	"/crm/contract-template": {"doctype": "Contract Template", "module": "crm", "classification": "generated_provisional"},
	"/crm/email-campaign": {"doctype": "Email Campaign", "module": "crm", "classification": "generated_provisional"},
	"/crm/gender": {"doctype": "Gender", "module": "crm", "classification": "generated_provisional"},
	"/crm/lead-source": {"doctype": "Lead Source", "module": "crm", "classification": "generated_provisional"},
	"/crm/market-segment": {"doctype": "Market Segment", "module": "crm", "classification": "generated_provisional"},
	"/crm/opportunity-lost-reason": {"doctype": "Opportunity Lost Reason", "module": "crm", "classification": "generated_provisional"},
	"/crm/opportunity-type": {"doctype": "Opportunity Type", "module": "crm", "classification": "generated_provisional"},
	"/crm/prospect": {"doctype": "Prospect", "module": "crm", "classification": "generated_provisional"},
	"/crm/sales-stage": {"doctype": "Sales Stage", "module": "crm", "classification": "generated_provisional"},
	"/crm/salutation": {"doctype": "Salutation", "module": "crm", "classification": "generated_provisional"},
	"/finance/accounting-dimension": {"doctype": "Accounting Dimension", "module": "finance", "classification": "generated_provisional"},
	"/finance/accounting-dimension-filter": {"doctype": "Accounting Dimension Filter", "module": "finance", "classification": "generated_provisional"},
	"/finance/accounting-period": {"doctype": "Accounting Period", "module": "finance", "classification": "generated_provisional"},
	"/finance/bank": {"doctype": "Bank", "module": "finance", "classification": "generated_provisional"},
	"/finance/bank-account": {"doctype": "Bank Account", "module": "finance", "classification": "generated_provisional"},
	"/finance/bank-account-subtype": {"doctype": "Bank Account Subtype", "module": "finance", "classification": "generated_provisional"},
	"/finance/bank-account-type": {"doctype": "Bank Account Type", "module": "finance", "classification": "generated_provisional"},
	"/finance/bank-guarantee": {"doctype": "Bank Guarantee", "module": "finance", "classification": "generated_provisional"},
	"/finance/bank-statement-import": {"doctype": "Bank Statement Import", "module": "finance", "classification": "generated_provisional"},
	"/finance/bank-transaction": {"doctype": "Bank Transaction", "module": "finance", "classification": "generated_provisional"},
	"/finance/budget": {"doctype": "Budget", "module": "finance", "classification": "generated_provisional"},
	"/finance/cheque-print-template": {"doctype": "Cheque Print Template", "module": "finance", "classification": "generated_provisional"},
	"/finance/cost-center-allocation": {"doctype": "Cost Center Allocation", "module": "finance", "classification": "generated_provisional"},
	"/finance/coupon-code": {"doctype": "Coupon Code", "module": "finance", "classification": "generated_provisional"},
	"/finance/dunning": {"doctype": "Dunning", "module": "finance", "classification": "generated_provisional"},
	"/finance/dunning-type": {"doctype": "Dunning Type", "module": "finance", "classification": "generated_provisional"},
	"/finance/exchange-rate-revaluation": {"doctype": "Exchange Rate Revaluation", "module": "finance", "classification": "generated_provisional"},
	"/finance/finance-book": {"doctype": "Finance Book", "module": "finance", "classification": "generated_provisional"},
	"/finance/fiscal-year": {"doctype": "Fiscal Year", "module": "finance", "classification": "generated_provisional"},
	"/finance/invoice-discounting": {"doctype": "Invoice Discounting", "module": "finance", "classification": "generated_provisional"},
	"/finance/item-tax-template": {"doctype": "Item Tax Template", "module": "finance", "classification": "generated_provisional"},
	"/finance/journal-entry-template": {"doctype": "Journal Entry Template", "module": "finance", "classification": "generated_provisional"},
	"/finance/loyalty-program": {"doctype": "Loyalty Program", "module": "finance", "classification": "generated_provisional"},
	"/finance/monthly-distribution": {"doctype": "Monthly Distribution", "module": "finance", "classification": "generated_provisional"},
	"/finance/party-link": {"doctype": "Party Link", "module": "finance", "classification": "generated_provisional"},
	"/finance/payment-gateway-account": {"doctype": "Payment Gateway Account", "module": "finance", "classification": "generated_provisional"},
	"/finance/payment-order": {"doctype": "Payment Order", "module": "finance", "classification": "generated_provisional"},
	"/finance/payment-term": {"doctype": "Payment Term", "module": "finance", "classification": "generated_provisional"},
	"/finance/payment-terms-template": {"doctype": "Payment Terms Template", "module": "finance", "classification": "generated_provisional"},
	"/finance/period-closing-voucher": {"doctype": "Period Closing Voucher", "module": "finance", "classification": "generated_provisional"},
	# Bulk-processing "tool" doctypes (Process *) - regular submittable
	# doctypes (is_virtual/issingle/istable all falsy, confirmed against the
	# installed schema before routing), not virtual/single tools, so the
	# generic engine serves them exactly like any other transaction doctype.
	"/finance/process-period-closing-voucher": {"doctype": "Process Period Closing Voucher", "module": "finance", "classification": "generated_provisional"},
	"/finance/process-deferred-accounting": {"doctype": "Process Deferred Accounting", "module": "finance", "classification": "generated_provisional"},
	"/finance/process-statement-of-accounts": {"doctype": "Process Statement Of Accounts", "module": "finance", "classification": "generated_provisional"},
	"/finance/process-subscription": {"doctype": "Process Subscription", "module": "finance", "classification": "generated_provisional"},
	"/finance/unreconcile-payment": {"doctype": "Unreconcile Payment", "module": "finance", "classification": "generated_provisional"},
	"/finance/process-payment-reconciliation": {"doctype": "Process Payment Reconciliation", "module": "finance", "classification": "generated_provisional"},
	"/finance/process-payment-reconciliation-log": {"doctype": "Process Payment Reconciliation Log", "module": "finance", "classification": "generated_provisional"},
	"/finance/pricing-rule": {"doctype": "Pricing Rule", "module": "finance", "classification": "generated_provisional"},
	"/finance/promotional-scheme": {"doctype": "Promotional Scheme", "module": "finance", "classification": "generated_provisional"},
	"/finance/purchase-taxes-and-charges-template": {"doctype": "Purchase Taxes and Charges Template", "module": "finance", "classification": "generated_provisional"},
	"/finance/sales-taxes-and-charges-template": {"doctype": "Sales Taxes and Charges Template", "module": "finance", "classification": "generated_provisional"},
	"/finance/share-transfer": {"doctype": "Share Transfer", "module": "finance", "classification": "generated_provisional"},
	"/finance/share-type": {"doctype": "Share Type", "module": "finance", "classification": "generated_provisional"},
	"/finance/shareholder": {"doctype": "Shareholder", "module": "finance", "classification": "generated_provisional"},
	"/finance/shipping-rule": {"doctype": "Shipping Rule", "module": "finance", "classification": "generated_provisional"},
	"/finance/subscription": {"doctype": "Subscription", "module": "finance", "classification": "generated_provisional"},
	"/finance/subscription-plan": {"doctype": "Subscription Plan", "module": "finance", "classification": "generated_provisional"},
	"/finance/tax-category": {"doctype": "Tax Category", "module": "finance", "classification": "generated_provisional"},
	"/finance/tax-rule": {"doctype": "Tax Rule", "module": "finance", "classification": "generated_provisional"},
	"/finance/tax-withholding-category": {"doctype": "Tax Withholding Category", "module": "finance", "classification": "generated_provisional"},
	"/inventory/customs-tariff-number": {"doctype": "Customs Tariff Number", "module": "inventory", "classification": "generated_provisional"},
	"/inventory/delivery-trip": {"doctype": "Delivery Trip", "module": "inventory", "classification": "generated_provisional"},
	"/inventory/inventory-dimension": {"doctype": "Inventory Dimension", "module": "inventory", "classification": "generated_provisional"},
	"/inventory/item-alternative": {"doctype": "Item Alternative", "module": "inventory", "classification": "generated_provisional"},
	"/inventory/item-attribute": {"doctype": "Item Attribute", "module": "inventory", "classification": "generated_provisional"},
	"/inventory/item-manufacturer": {"doctype": "Item Manufacturer", "module": "inventory", "classification": "generated_provisional"},
	"/inventory/landed-cost-voucher": {"doctype": "Landed Cost Voucher", "module": "inventory", "classification": "generated_provisional"},
	"/inventory/manufacturer": {"doctype": "Manufacturer", "module": "inventory", "classification": "generated_provisional"},
	"/inventory/packing-slip": {"doctype": "Packing Slip", "module": "inventory", "classification": "generated_provisional"},
	"/inventory/pick-list": {"doctype": "Pick List", "module": "inventory", "classification": "generated_provisional"},
	"/inventory/putaway-rule": {"doctype": "Putaway Rule", "module": "inventory", "classification": "generated_provisional"},
	"/inventory/quality-inspection-parameter": {"doctype": "Quality Inspection Parameter", "module": "inventory", "classification": "generated_provisional"},
	"/inventory/quality-inspection-parameter-group": {"doctype": "Quality Inspection Parameter Group", "module": "inventory", "classification": "generated_provisional"},
	"/inventory/quality-inspection-template": {"doctype": "Quality Inspection Template", "module": "inventory", "classification": "generated_provisional"},
	"/inventory/shipment": {"doctype": "Shipment", "module": "inventory", "classification": "generated_provisional"},
	"/inventory/shipment-parcel-template": {"doctype": "Shipment Parcel Template", "module": "inventory", "classification": "generated_provisional"},
	"/inventory/serial-and-batch-bundle": {"doctype": "Serial and Batch Bundle", "module": "inventory", "classification": "generated_provisional"},
	"/inventory/stock-entry-type": {"doctype": "Stock Entry Type", "module": "inventory", "classification": "generated_provisional"},
	"/inventory/stock-reservation-entry": {"doctype": "Stock Reservation Entry", "module": "inventory", "classification": "generated_provisional"},
	"/inventory/uom-category": {"doctype": "UOM Category", "module": "inventory", "classification": "generated_provisional"},
	"/inventory/warehouse-type": {"doctype": "Warehouse Type", "module": "inventory", "classification": "generated_provisional"},
	"/operations/activity-cost": {"doctype": "Activity Cost", "module": "operations", "classification": "generated_provisional"},
	"/operations/activity-type": {"doctype": "Activity Type", "module": "operations", "classification": "generated_provisional"},
	"/operations/asset-activity": {"doctype": "Asset Activity", "module": "operations", "classification": "generated_provisional"},
	"/operations/asset-capitalization": {"doctype": "Asset Capitalization", "module": "operations", "classification": "generated_provisional"},
	"/operations/asset-category": {"doctype": "Asset Category", "module": "operations", "classification": "generated_provisional"},
	"/operations/asset-maintenance": {"doctype": "Asset Maintenance", "module": "operations", "classification": "generated_provisional"},
	"/operations/asset-maintenance-log": {"doctype": "Asset Maintenance Log", "module": "operations", "classification": "generated_provisional"},
	"/operations/asset-maintenance-team": {"doctype": "Asset Maintenance Team", "module": "operations", "classification": "generated_provisional"},
	"/operations/asset-repair": {"doctype": "Asset Repair", "module": "operations", "classification": "generated_provisional"},
	"/operations/asset-shift-allocation": {"doctype": "Asset Shift Allocation", "module": "operations", "classification": "generated_provisional"},
	"/operations/asset-shift-factor": {"doctype": "Asset Shift Factor", "module": "operations", "classification": "generated_provisional"},
	"/operations/asset-value-adjustment": {"doctype": "Asset Value Adjustment", "module": "operations", "classification": "generated_provisional"},
	"/operations/issue-priority": {"doctype": "Issue Priority", "module": "operations", "classification": "generated_provisional"},
	"/operations/issue-type": {"doctype": "Issue Type", "module": "operations", "classification": "generated_provisional"},
	"/operations/location": {"doctype": "Location", "module": "operations", "classification": "generated_provisional", "view": "tree"},
	"/operations/non-conformance": {"doctype": "Non Conformance", "module": "operations", "classification": "generated_provisional"},
	"/operations/project-template": {"doctype": "Project Template", "module": "operations", "classification": "generated_provisional"},
	"/operations/project-type": {"doctype": "Project Type", "module": "operations", "classification": "generated_provisional"},
	"/operations/project-update": {"doctype": "Project Update", "module": "operations", "classification": "generated_provisional"},
	"/operations/quality-action": {"doctype": "Quality Action", "module": "operations", "classification": "generated_provisional"},
	"/operations/quality-feedback": {"doctype": "Quality Feedback", "module": "operations", "classification": "generated_provisional"},
	"/operations/quality-feedback-template": {"doctype": "Quality Feedback Template", "module": "operations", "classification": "generated_provisional"},
	"/operations/quality-goal": {"doctype": "Quality Goal", "module": "operations", "classification": "generated_provisional"},
	"/operations/quality-meeting": {"doctype": "Quality Meeting", "module": "operations", "classification": "generated_provisional"},
	"/operations/quality-procedure": {"doctype": "Quality Procedure", "module": "operations", "classification": "generated_provisional", "view": "tree"},
	"/operations/quality-review": {"doctype": "Quality Review", "module": "operations", "classification": "generated_provisional"},
	"/operations/service-level-agreement": {"doctype": "Service Level Agreement", "module": "operations", "classification": "generated_provisional"},
	"/operations/task-type": {"doctype": "Task Type", "module": "operations", "classification": "generated_provisional"},
	"/operations/timesheet": {"doctype": "Timesheet", "module": "operations", "classification": "generated_provisional"},
	"/operations/warranty-claim": {"doctype": "Warranty Claim", "module": "operations", "classification": "generated_provisional"},
	"/purchases/supplier-scorecard": {"doctype": "Supplier Scorecard", "module": "purchases", "classification": "generated_provisional"},
	"/purchases/supplier-scorecard-criteria": {"doctype": "Supplier Scorecard Criteria", "module": "purchases", "classification": "generated_provisional"},
	"/purchases/supplier-scorecard-period": {"doctype": "Supplier Scorecard Period", "module": "purchases", "classification": "generated_provisional"},
	"/purchases/supplier-scorecard-standing": {"doctype": "Supplier Scorecard Standing", "module": "purchases", "classification": "generated_provisional"},
	"/purchases/supplier-scorecard-variable": {"doctype": "Supplier Scorecard Variable", "module": "purchases", "classification": "generated_provisional"},
	"/sales/industry-type": {"doctype": "Industry Type", "module": "sales", "classification": "generated_provisional"},
	"/sales/installation-note": {"doctype": "Installation Note", "module": "sales", "classification": "generated_provisional"},
	"/sales/party-specific-item": {"doctype": "Party Specific Item", "module": "sales", "classification": "generated_provisional"},
	"/sales/product-bundle": {"doctype": "Product Bundle", "module": "sales", "classification": "generated_provisional"},
	"/sales/sales-partner-type": {"doctype": "Sales Partner Type", "module": "sales", "classification": "generated_provisional"},
}
ENTITY_ROUTES.update(_GENERATED_ENTITY_ROUTES)


# --- Generated in-scope DocType routes (Full Feature Parity, batch: final-mapping masters) ---
# Remaining safe non-table, non-single, non-ledger master DocTypes from Accounts,
# Setup, Printing, Regional, Selling and POSAwesome. Settings singletons, repair/
# repost tools, reconciliation wizards and ledger tables (GL Entry, Payment Ledger
# Entry, Stock Ledger Entry, Bin, Serial and Batch Bundle, etc.) are deliberately
# excluded here — see parity_registry.INTERNAL_DOCTYPE_NAMES / special_adapter work.
_GENERATED_ENTITY_ROUTES_2 = {
	"/operations/employee": {"doctype": "Employee", "module": "operations", "classification": "generated_provisional"},
	"/operations/employee-group": {"doctype": "Employee Group", "module": "operations", "classification": "generated_provisional"},
	"/operations/holiday-list": {"doctype": "Holiday List", "module": "operations", "classification": "generated_provisional"},
	"/operations/driver": {"doctype": "Driver", "module": "operations", "classification": "generated_provisional"},
	"/operations/vehicle": {"doctype": "Vehicle", "module": "operations", "classification": "generated_provisional"},
	"/admin/branch": {"doctype": "Branch", "module": "admin", "classification": "generated_provisional"},
	"/admin/print-heading": {"doctype": "Print Heading", "module": "admin", "classification": "generated_provisional"},
	"/admin/authorization-rule": {"doctype": "Authorization Rule", "module": "admin", "classification": "generated_provisional"},
	"/admin/email-digest": {"doctype": "Email Digest", "module": "admin", "classification": "generated_provisional"},
	"/admin/letter-head": {"doctype": "Letter Head", "module": "admin", "classification": "generated_provisional"},
	"/admin/print-format": {"doctype": "Print Format", "module": "admin", "classification": "generated_provisional"},
	"/admin/print-format-field-template": {"doctype": "Print Format Field Template", "module": "admin", "classification": "generated_provisional"},
	"/admin/print-style": {"doctype": "Print Style", "module": "admin", "classification": "generated_provisional"},
	"/purchases/incoterm": {"doctype": "Incoterm", "module": "purchases", "classification": "generated_provisional"},
	"/finance/party-type": {"doctype": "Party Type", "module": "finance", "classification": "generated_provisional"},
	"/finance/currency-exchange": {"doctype": "Currency Exchange", "module": "finance", "classification": "generated_provisional"},
	"/finance/lower-deduction-certificate": {"doctype": "Lower Deduction Certificate", "module": "finance", "classification": "generated_provisional"},
	"/sales/quotation-lost-reason": {"doctype": "Quotation Lost Reason", "module": "sales", "classification": "generated_provisional"},
	"/sales/sales-partner": {"doctype": "Sales Partner", "module": "sales", "classification": "generated_provisional"},
	"/sales/terms-and-conditions": {"doctype": "Terms and Conditions", "module": "sales", "classification": "generated_provisional"},
	"/sales/pos-coupon": {"doctype": "POS Coupon", "module": "sales", "classification": "generated_provisional"},
	"/sales/pos-gift-card": {"doctype": "POS Gift Card", "module": "sales", "classification": "generated_provisional"},
	"/sales/pos-offer": {"doctype": "POS Offer", "module": "sales", "classification": "generated_provisional"},
	"/sales/delivery-charges": {"doctype": "Delivery Charges", "module": "sales", "classification": "generated_provisional"},
	"/sales/referral-code": {"doctype": "Referral Code", "module": "sales", "classification": "generated_provisional"},
	"/inventory/uom-conversion-factor": {"doctype": "UOM Conversion Factor", "module": "inventory", "classification": "generated_provisional"},
}
ENTITY_ROUTES.update(_GENERATED_ENTITY_ROUTES_2)


FORM_VARIANTS = {
	"/inventory/transfers/new": {"doctype": "Stock Entry", "module": "inventory", "base_path": "/inventory/stock-entries", "defaults": {"stock_entry_type": "Material Transfer"}},
	"/inventory/receipts/new": {"doctype": "Stock Entry", "module": "inventory", "base_path": "/inventory/stock-entries", "defaults": {"stock_entry_type": "Material Receipt"}},
	"/inventory/issues/new": {"doctype": "Stock Entry", "module": "inventory", "base_path": "/inventory/stock-entries", "defaults": {"stock_entry_type": "Material Issue"}},
}


SPECIAL_ROUTES = {
	"/sales/funnel": {"module": "sales", "label": "Sales Funnel", "page": "sales-funnel", "classification": "specialised_provisional"},
	"/sales/transactions": {"module": "sales", "label": "Wholesale Transactions", "classification": "register"},
	"/inventory/reorder-alerts": {"module": "inventory", "label": "Reorder Alerts", "report": "Stock Projected Qty", "classification": "report", "alias": "/reports/view/Stock%20Projected%20Qty"},
	"/inventory/warehouse-capacity": {"module": "inventory", "label": "Warehouse Capacity Summary", "page": "warehouse-capacity-summary", "classification": "specialised_provisional"},
	"/finance/payment-reconciliation": {"module": "finance", "label": "Payment Reconciliation", "doctype": "Payment Reconciliation", "classification": "specialised_provisional"},
	"/finance/bank-reconciliation": {"module": "finance", "label": "Bank Reconciliation", "doctype": "Bank Reconciliation Tool", "classification": "specialised_provisional"},
	"/finance/bank-clearance": {"module": "finance", "label": "Bank Clearance", "doctype": "Bank Clearance", "classification": "specialised_provisional"},
	"/finance/pegged-currencies": {"module": "finance", "label": "Pegged Currencies", "doctype": "Pegged Currencies", "classification": "specialised_provisional"},
	"/crm/customers": {"module": "crm", "label": "Customers", "alias": "/sales/customers", "doctype": "Customer"},
	"/operations/manufacturing": {"module": "operations", "label": "Manufacturing", "doctypes": ("BOM", "Production Plan", "Work Order", "Job Card")},
	"/operations/subcontracting": {"module": "operations", "label": "Subcontracting", "doctypes": ("Subcontracting Order", "Subcontracting Receipt")},
	"/pos": {"module": "sales", "label": "Point of Sale", "doctype": "POS Profile", "classification": "safe_integration"},
	"/admin/permissions": {"module": "admin", "label": "Role Permissions", "page": "permission-manager", "roles": ("System Manager",)},
	"/admin/settings": {"module": "admin", "label": "Settings", "doctypes": ("System Settings",), "roles": ("System Manager",), "classification": "read_only"},
	"/admin/integrations": {"module": "admin", "label": "Integrations", "doctypes": ("OAuth Client", "Connected App"), "roles": ("System Manager",)},
	"/admin/website": {"module": "admin", "label": "Website", "doctypes": ("Website Settings", "Web Page"), "roles": ("System Manager",)},
	"/admin/system-health": {"module": "admin", "label": "System Health", "roles": ("System Manager",), "classification": "read_only"},
	"/admin/background-jobs": {"module": "admin", "label": "Background Jobs", "roles": ("System Manager",), "classification": "read_only"},
}


REPORT_GROUPS = {
	"sales": ("Sales Register", "Sales Order Analysis", "Customer Ledger Summary", "Item-wise Sales Register", "Sales Analytics"),
	"purchases": ("Purchase Register", "Purchase Order Analysis", "Supplier Ledger Summary", "Item-wise Purchase Register"),
	"inventory": ("Stock Balance", "Stock Ledger", "Stock Analytics", "Stock Projected Qty"),
	"finance": ("Accounts Receivable", "Accounts Payable", "General Ledger", "Trial Balance", "Profit and Loss Statement", "Balance Sheet", "Cash Flow", "Bank Reconciliation Statement"),
	"crm": ("CRM Analytics", "Lead Details", "Opportunity Summary by Sales Stage"),
	"operations": ("Project Summary", "Work Order Summary", "Asset Depreciation Ledger"),
}


REPORT_FILTERS = {
	"Sales Register": ("company", "from_date", "to_date", "customer"),
	"Sales Order Analysis": ("company", "from_date", "to_date", "customer"),
	# "party" (not "customer") is the real filter fieldname on this report
	# (erpnext/accounts/report/customer_ledger_summary/customer_ledger_summary.js);
	# fixed a pre-existing mismatch that meant the customer filter was silently
	# ignored by frappe.desk.query_report.run.
	"Customer Ledger Summary": ("company", "from_date", "to_date", "finance_book", "party", "customer_group", "payment_terms_template"),
	"Item-wise Sales Register": ("company", "from_date", "to_date", "item_code"),
	"Sales Analytics": ("company", "from_date", "to_date"),
	"Purchase Register": ("company", "from_date", "to_date", "supplier"),
	"Purchase Order Analysis": ("company", "from_date", "to_date", "supplier"),
	"Item-wise Purchase Register": ("company", "from_date", "to_date", "item_code"),
	"Stock Balance": ("company", "from_date", "to_date", "warehouse", "item_group", "item_code"),
	"Stock Ledger": ("company", "from_date", "to_date", "warehouse", "item_code", "batch_no"),
	"Stock Analytics": ("company", "from_date", "to_date", "warehouse"),
	"Stock Projected Qty": ("company", "warehouse", "item_group", "item_code"),
	# Filter fieldnames matched against each report's real Script Report .js
	# filter definitions (erpnext/accounts/report/<report>/<report>.js, and
	# the shared erpnext/public/js/financial_statements.js for P&L/Balance
	# Sheet/Cash Flow) — never guessed. "posting_date" -> "report_date" for
	# AR/AP corrects a pre-existing mismatch (the real filter fieldname on
	# both reports is report_date; posting_date was silently ignored by
	# frappe.desk.query_report.run).
	"Accounts Receivable": ("company", "report_date", "finance_book", "cost_center", "project", "party", "party_account", "ageing_based_on"),
	"Accounts Payable": ("company", "report_date", "finance_book", "cost_center", "project", "party", "party_account", "ageing_based_on"),
	"General Ledger": ("company", "finance_book", "from_date", "to_date", "account", "voucher_no", "party_type", "party", "presentation_currency", "cost_center", "project"),
	"Trial Balance": ("company", "fiscal_year", "period_start_date", "period_end_date", "cost_center", "project", "finance_book", "presentation_currency"),
	"Profit and Loss Statement": ("company", "finance_book", "filter_based_on", "period_start_date", "period_end_date", "from_fiscal_year", "to_fiscal_year", "periodicity", "presentation_currency", "cost_center", "project"),
	"Balance Sheet": ("company", "finance_book", "filter_based_on", "period_start_date", "period_end_date", "from_fiscal_year", "to_fiscal_year", "periodicity", "presentation_currency", "cost_center", "project"),
	# Cash Flow reuses erpnext.financial_statements' filter set but removes
	# presentation_currency (erpnext/accounts/report/cash_flow/cash_flow.js
	# splices it out); cost_center/project remain.
	"Cash Flow": ("company", "finance_book", "filter_based_on", "period_start_date", "period_end_date", "from_fiscal_year", "to_fiscal_year", "periodicity", "cost_center", "project"),
	"Bank Reconciliation Statement": ("company", "bank_account", "from_date", "to_date"),
	"Supplier Ledger Summary": ("company", "from_date", "to_date", "finance_book", "party", "supplier_group", "payment_terms_template"),
}


# --- Generated in-scope report coverage (Full Feature Parity, batch: reports) ---
# In-scope standard reports served by the existing permission-aware report
# viewer (get_priority_report_definition / run_priority_report). Filters are
# derived from each report's discovered filter fieldnames. generated_provisional.
_GENERATED_REPORT_GROUPS = {
	'sales': (
		'Address And Contacts',
		'Available Stock for Packing Items',
		'Customer Acquisition and Loyalty',
		'Customer Credit Balance',
		'Customer-wise Item Price',
		'Customers Without Any Sales Transactions',
		'Inactive Customers',
		'Item-wise Sales History',
		'Lost Quotations',
		'Payment Terms Status for Sales Order',
		'Pending SO Items For Purchase Request',
		'Quotation Trends',
		'Sales Order Trends',
		'Sales Partner Commission Summary',
		'Sales Partner Target Variance based on Item Group',
		'Sales Partner Transaction Summary',
		'Sales Person Commission Summary',
		'Sales Person Target Variance Based On Item Group',
		'Sales Person-wise Transaction Summary',
		'Territory Target Variance Based On Item Group',
		'Territory-wise Sales',
	),
	'purchases': (
		'Item-wise Purchase History',
		'Procurement Tracker',
		'Purchase Analytics',
		'Purchase Order Trends',
		'Requested Items to Order and Receive',
		'Subcontract Order Summary',
		'Subcontracted Item To Be Received',
		'Subcontracted Raw Materials To Be Transferred',
		'Supplier Quotation Comparison',
	),
	'inventory': (
		'Available Batch Report',
		'Available Serial No',
		'BOM Search',
		'Batch Item Expiry Status',
		'Batch-Wise Balance History',
		'COGS By Item Group',
		'Delayed Item Report',
		'Delayed Order Report',
		'Delivery Note Trends',
		'FIFO Queue vs Qty After Transaction Comparison',
		'Incorrect Balance Qty After Transaction',
		'Incorrect Serial No Valuation',
		'Incorrect Serial and Batch Bundle',
		'Incorrect Stock Value Report',
		'Item Balance (Simple)',
		'Item Price Stock',
		'Item Prices',
		'Item Shortage Report',
		'Item Variant Details',
		'Item Wise Consumption',
		'Item-wise Price List Rate',
		'Items To Be Requested',
		'Itemwise Recommended Reorder Level',
		'Landed Cost Report',
		'Material Requests for which Supplier Quotations are not created',
		'Negative Batch Report',
		'Product Bundle Balance',
		'Purchase Receipt Trends',
		'Requested Items To Be Transferred',
		'Reserved Stock',
		'Serial No Ledger',
		'Serial No Service Contract Expiry',
		'Serial No Status',
		'Serial No Warranty Expiry',
		'Serial No and Batch Traceability',
		'Serial and Batch Summary',
		'Stock Ageing',
		'Stock Ledger Invariant Check',
		'Stock Ledger Variance',
		'Stock Qty vs Batch Qty',
		'Stock Qty vs Serial No Count',
		'Stock and Account Value Comparison',
		'Supplier-Wise Sales Analytics',
		'Total Stock Summary',
		'Warehouse Wise Stock Balance',
		'Warehouse wise Item Balance Age and Value',
	),
	'finance': (
		'Account Balance',
		'Accounts Payable Summary',
		'Accounts Receivable Summary',
		'Asset Depreciations and Balances',
		'Bank Clearance Summary',
		'Billed Items To Be Received',
		'Budget Variance Report',
		'Calculated Discount Mismatch',
		'Cheques and Deposits Incorrectly cleared',
		'Consolidated Financial Statement',
		'Consolidated Trial Balance',
		'Custom Financial Statement',
		'Deferred Revenue and Expense',
		'Delivered Items To Be Billed',
		'Dimension-wise Accounts Balance Report',
		'Financial Ratios',
		'General and Payment Ledger Comparison',
		'Gross Profit',
		'Gross and Net Profit Report',
		'Inactive Sales Items',
		'Invalid Ledger Entries',
		'POS Register',
		'Payment Ledger',
		'Payment Period Based On Invoice Date',
		'Profitability Analysis',
		'Purchase Invoice Trends',
		'Received Items To Be Billed',
		'Sales Invoice Trends',
		'Sales Partners Commission',
		'Sales Payment Summary',
		'Share Balance',
		'Share Ledger',
		'TDS Computation Summary',
		'Tax Withholding Details',
		'Trial Balance (Simple)',
		'Trial Balance for Party',
		'Voucher-wise Balance',
	),
	'crm': (
		'Campaign Efficiency',
		'First Response Time for Opportunity',
		'Lead Conversion Time',
		'Lead Owner Efficiency',
		'Lost Opportunity',
		'Prospects Engaged But Not Converted',
		'Sales Pipeline Analytics',
		'Addresses And Contacts',
	),
	'operations': (
		'Asset Activity',
		'Asset Maintenance',
		'BOM Explorer',
		'BOM Operations Time',
		'BOM Stock Analysis',
		'BOM Stock Calculated',
		'BOM Stock Report',
		'BOM Variance Report',
		'Completed Work Orders',
		'Cost of Poor Quality Report',
		'Daily Timesheet Summary',
		'Delayed Tasks Summary',
		'Downtime Analysis',
		'Employee Billing Summary',
		'Exponential Smoothing Forecasting',
		'First Response Time for Issues',
		'Fixed Asset Register',
		'Issue Analytics',
		'Issue Summary',
		'Issued Items Against Work Order',
		'Job Card Summary',
		'Material Requirements Planning Report',
		'Open Work Orders',
		'Process Loss Report',
		'Production Analytics',
		'Production Plan Summary',
		'Production Planning Report',
		'Project Billing Summary',
		'Project wise Stock Tracking',
		'Quality Inspection Summary',
		'Review',
		'Support Hour Distribution',
		'Timesheet Billing Summary',
		'Work Order Consumed Materials',
		'Work Order Stock Report',
		'Work Orders in Progress',
	),
}
for _grp, _names in _GENERATED_REPORT_GROUPS.items():
	REPORT_GROUPS[_grp] = tuple(dict.fromkeys(REPORT_GROUPS.get(_grp, ()) + _names))

_GENERATED_REPORT_FILTERS = {
	'Account Balance': ('company',),
	'Accounts Payable Summary': ('ageing_based_on', 'company', 'cost_center', 'party', 'party_type', 'project', 'range', 'supplier_group'),
	'Accounts Receivable Summary': ('ageing_based_on', 'company', 'cost_center', 'customer_group', 'party', 'party_type', 'project', 'range'),
	'Address And Contacts': ('party_type',),
	'Asset Activity': ('company', 'from_date', 'to_date'),
	'Asset Depreciations and Balances': ('company', 'from_date', 'group_by', 'to_date'),
	'Asset Maintenance': ('company', 'from_date', 'to_date'),
	'Available Batch Report': ('batch_no', 'company', 'item_code', 'to_date', 'warehouse'),
	'Available Serial No': ('company', 'from_date', 'item_code', 'to_date', 'voucher_no', 'warehouse'),
	'Available Stock for Packing Items': ('company', 'from_date', 'to_date'),
	'BOM Explorer': ('company', 'from_date', 'to_date'),
	'BOM Operations Time': ('item_code',),
	'BOM Search': ('company', 'from_date', 'to_date'),
	'BOM Stock Analysis': ('company', 'from_date', 'to_date'),
	'BOM Stock Calculated': ('warehouse',),
	'BOM Stock Report': ('warehouse',),
	'BOM Variance Report': ('company', 'from_date', 'to_date'),
	'Bank Clearance Summary': ('account', 'from_date', 'to_date'),
	'Batch Item Expiry Status': ('from_date', 'item', 'to_date'),
	'Batch-Wise Balance History': ('batch_no', 'company', 'from_date', 'item_code', 'to_date', 'warehouse'),
	'Billed Items To Be Received': ('company', 'posting_date'),
	'Budget Variance Report': ('company', 'from_fiscal_year', 'to_fiscal_year'),
	'COGS By Item Group': ('company', 'from_date', 'to_date'),
	'Calculated Discount Mismatch': ('company', 'from_date', 'to_date'),
	'Campaign Efficiency': ('from_date', 'to_date'),
	'Cheques and Deposits Incorrectly cleared': ('account', 'company'),
	'Completed Work Orders': ('company', 'from_date', 'to_date'),
	'Consolidated Financial Statement': ('company', 'from_fiscal_year', 'period_end_date', 'period_start_date', 'to_fiscal_year'),
	'Consolidated Trial Balance': ('company', 'from_date', 'to_date'),
	'Cost of Poor Quality Report': ('batch_no', 'company', 'from_date', 'serial_no', 'to_date'),
	'Custom Financial Statement': ('company', 'from_date', 'to_date'),
	'Customer Acquisition and Loyalty': ('company', 'from_date', 'to_date'),
	'Customer Credit Balance': ('company', 'customer'),
	'Customer-wise Item Price': ('customer', 'item'),
	'Customers Without Any Sales Transactions': ('company', 'from_date', 'to_date'),
	'Daily Timesheet Summary': ('from_date', 'to_date'),
	'Deferred Revenue and Expense': ('company', 'from_fiscal_year', 'period_end_date', 'period_start_date', 'periodicity', 'to_fiscal_year'),
	'Delayed Item Report': ('based_on', 'company', 'customer', 'customer_group', 'from_date', 'item_group', 'to_date'),
	'Delayed Order Report': ('based_on', 'company', 'customer', 'customer_group', 'from_date', 'item_group', 'to_date'),
	'Delayed Tasks Summary': ('from_date', 'project', 'status', 'to_date'),
	'Delivered Items To Be Billed': ('company', 'posting_date'),
	'Delivery Note Trends': ('company', 'from_date', 'to_date'),
	'Dimension-wise Accounts Balance Report': ('company', 'fiscal_year', 'from_date', 'to_date'),
	'Downtime Analysis': ('from_date', 'to_date'),
	'Employee Billing Summary': ('from_date', 'to_date'),
	'Exponential Smoothing Forecasting': ('company', 'from_date', 'item_code', 'periodicity', 'to_date', 'warehouse'),
	'FIFO Queue vs Qty After Transaction Comparison': ('from_date', 'item_code', 'item_group', 'to_date', 'warehouse'),
	'Financial Ratios': ('company', 'from_fiscal_year', 'period_end_date', 'period_start_date', 'periodicity', 'to_fiscal_year'),
	'First Response Time for Issues': ('from_date', 'to_date'),
	'First Response Time for Opportunity': ('from_date', 'to_date'),
	'Fixed Asset Register': ('company', 'cost_center', 'from_date', 'from_fiscal_year', 'group_by', 'status', 'to_date', 'to_fiscal_year'),
	'General and Payment Ledger Comparison': ('account', 'company', 'party', 'party_type', 'period_end_date', 'period_start_date', 'voucher_no'),
	'Gross Profit': ('company', 'cost_center', 'from_date', 'group_by', 'item_group', 'project', 'sales_person', 'to_date'),
	'Gross and Net Profit Report': ('company', 'from_date', 'to_date'),
	'Inactive Customers': ('company', 'from_date', 'to_date'),
	'Inactive Sales Items': ('based_on', 'item', 'item_group', 'territory'),
	'Incorrect Balance Qty After Transaction': ('company', 'item_code', 'warehouse'),
	'Incorrect Serial No Valuation': ('from_date', 'item_code', 'to_date'),
	'Incorrect Serial and Batch Bundle': ('item_code', 'warehouse'),
	'Incorrect Stock Value Report': ('account', 'company', 'from_date'),
	'Invalid Ledger Entries': ('account', 'company', 'from_date', 'to_date', 'voucher_no'),
	'Issue Analytics': ('based_on', 'company', 'customer', 'from_date', 'project', 'range', 'status', 'to_date'),
	'Issue Summary': ('based_on', 'company', 'customer', 'from_date', 'project', 'status', 'to_date'),
	'Issued Items Against Work Order': ('company', 'from_date', 'to_date'),
	'Item Balance (Simple)': ('company', 'from_date', 'to_date'),
	'Item Price Stock': ('item_code',),
	'Item Prices': ('company', 'from_date', 'to_date'),
	'Item Shortage Report': ('company', 'warehouse'),
	'Item Variant Details': ('item',),
	'Item Wise Consumption': ('company', 'from_date', 'to_date'),
	'Item-wise Price List Rate': ('company', 'from_date', 'to_date'),
	'Item-wise Purchase History': ('company', 'from_date', 'item_code', 'item_group', 'supplier', 'to_date'),
	'Item-wise Sales History': ('company', 'customer', 'from_date', 'item_code', 'item_group', 'to_date'),
	'Items To Be Requested': ('company', 'from_date', 'to_date'),
	'Itemwise Recommended Reorder Level': ('brand', 'from_date', 'item_group', 'to_date'),
	'Job Card Summary': ('company', 'fiscal_year', 'from_date', 'status', 'to_date'),
	'Landed Cost Report': ('company', 'from_date', 'to_date'),
	'Lead Conversion Time': ('from_date', 'to_date'),
	'Lead Owner Efficiency': ('from_date', 'to_date'),
	'Lost Opportunity': ('company', 'from_date', 'territory', 'to_date'),
	'Lost Quotations': ('company', 'group_by'),
	'Material Requests for which Supplier Quotations are not created': ('company', 'from_date', 'to_date'),
	'Material Requirements Planning Report': ('company', 'from_date', 'to_date'),
	'Negative Batch Report': ('company', 'item_code', 'warehouse'),
	'Open Work Orders': ('company', 'from_date', 'to_date'),
	'POS Register': ('company', 'customer', 'from_date', 'group_by', 'to_date'),
	'Payment Ledger': ('account', 'company', 'party', 'party_type', 'period_end_date', 'period_start_date', 'posting_date', 'voucher_no'),
	'Payment Period Based On Invoice Date': ('company', 'from_date', 'party', 'party_type', 'to_date'),
	'Payment Terms Status for Sales Order': ('company', 'customer', 'customer_group', 'item', 'item_group', 'period_end_date', 'period_start_date', 'status'),
	'Pending SO Items For Purchase Request': ('company', 'from_date', 'to_date'),
	'Process Loss Report': ('company', 'from_date', 'item', 'to_date'),
	'Procurement Tracker': ('company', 'cost_center', 'from_date', 'project', 'to_date'),
	'Product Bundle Balance': ('brand', 'company', 'item_code', 'item_group', 'warehouse'),
	'Production Analytics': ('company', 'from_date', 'range', 'to_date'),
	'Production Plan Summary': ('company', 'from_date', 'to_date'),
	'Production Planning Report': ('based_on', 'company'),
	'Profitability Analysis': ('based_on', 'company', 'fiscal_year', 'from_date', 'to_date'),
	'Project Billing Summary': ('from_date', 'project', 'to_date'),
	'Project wise Stock Tracking': ('company', 'from_date', 'to_date'),
	'Prospects Engaged But Not Converted': ('company', 'from_date', 'to_date'),
	'Purchase Analytics': ('company', 'from_date', 'range', 'to_date'),
	'Purchase Invoice Trends': ('company', 'from_date', 'to_date'),
	'Purchase Order Trends': ('company', 'from_date', 'to_date'),
	'Purchase Receipt Trends': ('company', 'from_date', 'to_date'),
	'Quality Inspection Summary': ('from_date', 'item_code', 'status', 'to_date'),
	'Quotation Trends': ('company', 'from_date', 'to_date'),
	'Received Items To Be Billed': ('company', 'posting_date'),
	'Requested Items To Be Transferred': ('company', 'from_date', 'to_date'),
	'Requested Items to Order and Receive': ('company', 'from_date', 'item_code', 'to_date'),
	'Reserved Stock': ('company', 'from_date', 'item_code', 'project', 'status', 'to_date', 'voucher_no', 'warehouse', 'from_voucher_type', 'from_voucher_no'),
	'Review': ('company', 'from_date', 'to_date'),
	'Sales Invoice Trends': ('company', 'from_date', 'to_date'),
	'Sales Order Trends': ('company', 'from_date', 'to_date'),
	'Sales Partner Commission Summary': ('company', 'customer', 'from_date', 'sales_partner', 'territory', 'to_date'),
	'Sales Partner Target Variance based on Item Group': ('company', 'fiscal_year'),
	'Sales Partner Transaction Summary': ('brand', 'company', 'customer', 'from_date', 'item_group', 'sales_partner', 'territory', 'to_date'),
	'Sales Partners Commission': ('company', 'from_date', 'to_date'),
	'Sales Payment Summary': ('company', 'from_date', 'to_date'),
	'Sales Person Commission Summary': ('company', 'customer', 'from_date', 'sales_person', 'territory', 'to_date'),
	'Sales Person Target Variance Based On Item Group': ('company', 'fiscal_year'),
	'Sales Person-wise Transaction Summary': ('brand', 'company', 'customer', 'from_date', 'item_group', 'sales_person', 'territory', 'to_date'),
	'Sales Pipeline Analytics': ('based_on', 'company', 'from_date', 'range', 'status', 'to_date'),
	'Serial No Ledger': ('item_code', 'posting_date', 'serial_no', 'warehouse'),
	'Serial No Service Contract Expiry': ('company', 'from_date', 'to_date'),
	'Serial No Status': ('company', 'from_date', 'to_date'),
	'Serial No Warranty Expiry': ('company', 'from_date', 'to_date'),
	'Serial No and Batch Traceability': ('company', 'from_date', 'to_date'),
	'Serial and Batch Summary': ('batch_no', 'company', 'from_date', 'item_code', 'serial_no', 'to_date', 'voucher_no', 'warehouse'),
	'Share Balance': ('company', 'from_date', 'to_date'),
	'Share Ledger': ('company', 'from_date', 'to_date'),
	'Stock Ageing': ('brand', 'company', 'item_code', 'range', 'to_date', 'warehouse'),
	'Stock Ledger Invariant Check': ('item_code', 'warehouse'),
	'Stock Ledger Variance': ('company', 'item_code', 'warehouse'),
	'Stock Qty vs Batch Qty': ('item',),
	'Stock Qty vs Serial No Count': ('company', 'warehouse'),
	'Stock and Account Value Comparison': ('account', 'company'),
	'Subcontract Order Summary': ('company', 'from_date', 'to_date'),
	'Subcontracted Item To Be Received': ('from_date', 'supplier', 'to_date'),
	'Subcontracted Raw Materials To Be Transferred': ('from_date', 'supplier', 'to_date'),
	'Supplier Quotation Comparison': ('company', 'from_date', 'item_code', 'supplier', 'to_date', 'request_for_quotation'),
	'Supplier-Wise Sales Analytics': ('from_date', 'supplier', 'to_date'),
	'Support Hour Distribution': ('from_date', 'to_date'),
	'TDS Computation Summary': ('company', 'from_date', 'party', 'party_type', 'to_date'),
	'Tax Withholding Details': ('company', 'from_date', 'party', 'party_type', 'to_date'),
	'Territory Target Variance Based On Item Group': ('company', 'fiscal_year'),
	'Territory-wise Sales': ('company',),
	'Timesheet Billing Summary': ('company', 'from_date', 'to_date'),
	'Total Stock Summary': ('company', 'group_by'),
	'Trial Balance (Simple)': ('company',),
	'Trial Balance for Party': ('account', 'company', 'fiscal_year', 'from_date', 'party', 'party_type', 'to_date'),
	'Voucher-wise Balance': ('company', 'from_date', 'to_date'),
	'Warehouse Wise Stock Balance': ('company',),
	'Warehouse wise Item Balance Age and Value': ('company', 'from_date', 'item_code', 'item_group', 'to_date', 'warehouse'),
	'Work Order Consumed Materials': ('company', 'from_date', 'status', 'to_date'),
	'Work Order Stock Report': ('warehouse',),
	'Work Orders in Progress': ('company', 'from_date', 'to_date'),
}
for _rn, _ff in _GENERATED_REPORT_FILTERS.items():
	REPORT_FILTERS.setdefault(_rn, _ff)


ALL_PRIORITY_DOCTYPES = frozenset(
	{spec["doctype"] for spec in ENTITY_ROUTES.values()}
	| {spec["doctype"] for spec in FORM_VARIANTS.values()}
	| {spec["doctype"] for spec in SPECIAL_ROUTES.values() if spec.get("doctype")}
)

CANONICAL_ROUTE_BY_DOCTYPE = {}
for _path, _spec in ENTITY_ROUTES.items():
	CANONICAL_ROUTE_BY_DOCTYPE.setdefault(_spec["doctype"], _path)


def routes_by_module() -> dict[str, list[tuple[str, dict]]]:
	result = defaultdict(list)
	for path, spec in ENTITY_ROUTES.items():
		result[spec["module"]].append((path, spec))
	for path, spec in SPECIAL_ROUTES.items():
		result[spec["module"]].append((path, spec))
	return dict(result)
