<script setup>
import { onBeforeUnmount, ref, watch } from "vue";
import { useRouter } from "vue-router";
import { createMappedDocument, executeSalesOrderAction, getMappedPreview, getSalesOrderActions } from "@/services/salesOrderActions.js";
const props = defineProps({ document: { type: Object, required: true } }); const emit = defineEmits(["refresh"]); const router = useRouter(); const data = ref(null); const error = ref(null); const busy = ref(false); const preview = ref(null); let controller;
async function load() { controller?.abort(); controller = new AbortController(); try { data.value = await getSalesOrderActions(props.document.name, controller.signal); } catch (requestError) { if (requestError.name !== "AbortError") error.value = requestError; } }
watch(() => props.document.modified, load, { immediate: true }); onBeforeUnmount(() => controller?.abort());
async function action(key) { if (busy.value) return; const labels = { submit: "Submit this Sales Order?", cancel: "Cancel this Sales Order?", amend: "Create an amendment draft?" }; if (!window.confirm(labels[key])) return; let params = {}; if (key === "cancel") { const reason = window.prompt("Optional cancellation reason:"); if (reason === null) return; params.reason = reason; } busy.value = true; error.value = null; try { const result = await executeSalesOrderAction(props.document.name, key, props.document.modified, params); await router.push(result.route); emit("refresh"); } catch (requestError) { error.value = requestError; } finally { busy.value = false; } }
async function map(target) { if (busy.value) return; busy.value = true; error.value = null; try { preview.value = await getMappedPreview(props.document.name, target, null, props.document.modified); } catch (requestError) { error.value = requestError; } finally { busy.value = false; } }
async function createMap() { busy.value = true; try { const selected = preview.value.items.map((item) => ({ name: item.source_row, qty: Number(item.transfer_qty) })); const result = await createMappedDocument(props.document.name, preview.value.target, selected, props.document.modified); preview.value = null; await router.push(result.route); } catch (requestError) { error.value = requestError; } finally { busy.value = false; } }
function print(format, pdf = false) { const query = new URLSearchParams({ doctype: "Sales Order", name: props.document.name, format, no_letterhead: "0" }); window.open(pdf ? `/api/method/frappe.utils.print_format.download_pdf?${query}` : `/printview?${query}`, "_blank", "noopener"); }
</script>
<template><section class="ref-so-actions"><header><div><span class="ref-entity-page__eyebrow">SALES ORDER LIFECYCLE</span><h2>Actions</h2></div><span v-if="busy" class="ref-status-badge" data-status="blue">Working…</span></header><p v-if="error" class="ref-action-error">{{ error.message }}</p><div v-if="data" class="ref-so-actions__buttons"><button v-for="entry in data.actions.filter((item) => !item.key.startsWith('create_'))" :key="entry.key" class="ref-button" :class="entry.key === 'submit' ? 'ref-button--primary' : 'ref-button--secondary'" :disabled="busy" @click="action(entry.key)">{{ entry.label }}</button><button v-if="data.actions.some((item) => item.key === 'create_delivery_note')" class="ref-button ref-button--green" :disabled="busy" @click="map('delivery_note')">Create Delivery Note</button><button v-if="data.actions.some((item) => item.key === 'create_sales_invoice')" class="ref-button ref-button--green" :disabled="busy" @click="map('sales_invoice')">Create Sales Invoice</button><template v-if="data.print.can_print"><button v-for="format in data.print.formats" :key="`print-${format.name}`" class="ref-button ref-button--secondary" :disabled="busy" @click="print(format.name)">Print {{ format.label }}</button><button class="ref-button ref-button--secondary" :disabled="busy" @click="print(data.print.formats[0]?.name || 'Standard', true)">Download PDF</button></template></div><div v-if="preview" class="ref-preview-modal" role="dialog" aria-modal="true"><div class="ref-preview-modal__backdrop" @click="preview = null"/><section><header><div><span class="ref-entity-page__eyebrow">MAPPED DOCUMENT PREVIEW</span><h2>{{ preview.target_doctype }}</h2><p>{{ preview.source }} · {{ preview.customer }}</p></div><button type="button" @click="preview = null">×</button></header><div class="ref-preview-items"><label v-for="item in preview.items" :key="item.source_row"><strong>{{ item.item_name || item.item_code }}</strong><small>Ordered {{ item.ordered_qty }} · Delivered {{ item.delivered_qty }} · Warehouse {{ item.warehouse || '—' }}</small><input v-model.number="item.transfer_qty" type="number" min="0.0001" :max="item.ordered_qty" step="any" /></label></div><footer><strong>{{ preview.currency }} {{ Number(preview.totals.grand_total || 0).toLocaleString() }}</strong><button class="ref-button ref-button--secondary" type="button" :disabled="busy" @click="preview = null">Back</button><button class="ref-button ref-button--primary" type="button" :disabled="busy" @click="createMap">{{ busy ? 'Creating…' : 'Create Draft' }}</button></footer></section></div></section></template>
